name: voice_control_timer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.6.3
  shared_preferences: ^2.0.15
  vosk_flutter_2: ^1.0.5
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/models/vosk-model-small-en-us-0.15/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_ios.png" # ← иконка без прозрачности для iOS
  adaptive_icon_foreground: "assets/images/foreground.png" # ← прозрачная
  adaptive_icon_background: "assets/images/background.png" # ← непрозрачная
  remove_alpha_ios: true # ← автоматически удалит прозрачность для iOS, даже если забудешь

flutter_native_splash:
  android: true
  ios: true
  android_12:
    image: assets/images/foreground.png
    icon_background_color: "#39B8F1" # цвет фона, соответствующий твоему background.png
    color: "#39B8F1"
  color: "#39B8F1"
  image: assets/images/foreground.png
